version: 2

jobs:
  build:
    docker:
    - image: circleci/golang:1.11

    steps:
    - checkout
    - run: go test -v ./...
    - run: go build ./...
    - run: ls
    - persist_to_workspace:
        root: .
        path:
        - loadtest

  push_image:
    docker:
    - image: circleci/golang:1.11

    steps:
    - checkout
    - setup_remote_docker
    - attach_workspace:
        at: .
    - run: docker login -u $DOCKER_LOGIN -p $DOCKER_PASSWORD
    - run: docker build -t quay.io/simonpasquier/loadtest:latest .
    - run: docker push quay.io/simonpasquier/loadtest


workflows:
  version: 2
  prometheus:
    jobs:
    - build:
        filters:
          tags:
            only: /.*/
    - push_image:
        requires:
        - build
        filters:
          branches:
            only: master
